application: vsd-storage
version: 1
runtime: python
api_version: 1

handlers:

# This deals with all kind of broken links and people that don't know how to
# configure their bt clients, contains a meta-refresh which only browsers
# can handle. Saves some bw and cpu avoiding the trigger of 404 errors.
# To save some more bw point this to static/null.html
- url: /static/
  static_dir: static

- url: /
  static_files: static/index.html
  upload: static/(.*)

- url: /favicon.ico
  static_files: static/imgs/favicon.ico
  upload: static/imgs/favicon.ico

- url: /util/(.*)
  script: util.py

- url: /(.*)
  script: proxy.py 

builtins:
- datastore_admin: on